import { Trip, User } from "../types/trip";


// Dummy users
export const users: User[] = [
  { id: "u1", name: "Alice", email: "alice@tiet.ac.in", phone: "1111", contacts: ["2222", "3333"] },
  { id: "u2", name: "Bob", email: "bob@tiet.ac.in", phone: "2222", contacts: ["1111", "4444"] },
  { id: "u3", name: "Charlie", email: "charlie@tiet.ac.in", phone: "3333", contacts: ["1111"] },
  { id: "u4", name: "Daisy", email: "daisy@tiet.ac.in", phone: "4444", contacts: ["5555"] },
  { id: "u5", name: "Eva", email: "eva@tiet.ac.in", phone: "5555", contacts: ["2222"] },
  { id: "u6", name: "Farhan", email: "farhan@tiet.ac.in", phone: "6666", contacts: ["7777", "8888"] },
  { id: "u7", name: "Gauri", email: "gauri@tiet.ac.in", phone: "7777", contacts: ["6666"] },
  { id: "u8", name: "Harsh", email: "harsh@tiet.ac.in", phone: "8888", contacts: ["6666"] },
  { id: "u9", name: "Isha", email: "isha@tiet.ac.in", phone: "9999", contacts: ["1111", "4444"] },
  { id: "u10", name: "Jay", email: "jay@tiet.ac.in", phone: "1010", contacts: ["9999","1111","4444","7777"], },
];

// Dummy trips (28 trips total)
export const trips: Trip[] = [
  // 1–10 (already provided earlier)
  {
    id: "t1",
    creatorId: "u1",
    start: "TIET, Patiala",
    destination: "Chandigarh",
    date: "2025-09-10",
    groupSize: 4,
    members: ["u1", "u2"],
    availableSeats: 2,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Rajpura", "Zirakpur"],
    users: [{ id: "u1", gender: "female" }, { id: "u2", gender: "male" }],
  },
  {
    id: "t2",
    creatorId: "u3",
    start: "TIET, Patiala",
    destination: "Delhi",
    date: "2025-09-11",
    groupSize: 5,
    members: ["u3"],
    availableSeats: 4,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Ambala", "Panipat"],
    users: [{ id: "u3", gender: "male" }],
  },
  {
    id: "t3",
    creatorId: "u4",
    start: "Patiala",
    destination: "Amritsar",
    date: "2025-09-12",
    groupSize: 3,
    members: ["u4", "u5"],
    availableSeats: 1,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Ludhiana", "Jalandhar"],
    users: [{ id: "u4", gender: "female" }, { id: "u5", gender: "female" }],
  },
  {
    id: "t4",
    creatorId: "u6",
    start: "TIET, Patiala",
    destination: "Jaipur",
    date: "2025-09-15",
    groupSize: 6,
    members: ["u6", "u7"],
    availableSeats: 4,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Ambala", "Rewari"],
    users: [{ id: "u6", gender: "male" }, { id: "u7", gender: "female" }],
  },
  {
    id: "t5",
    creatorId: "u8",
    start: "Chandigarh",
    destination: "Shimla",
    date: "2025-09-16",
    groupSize: 4,
    members: ["u8", "u9"],
    availableSeats: 2,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Solan", "Kalka"],
    users: [{ id: "u8", gender: "male" }, { id: "u9", gender: "female" }],
  },
  {
    id: "t6",
    creatorId: "u10",
    start: "TIET, Patiala",
    destination: "Ludhiana",
    date: "2025-09-17",
    groupSize: 3,
    members: ["u10"],
    availableSeats: 2,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Samana", "Khanna"],
    users: [{ id: "u10", gender: "male" }],
  },
  {
    id: "t7",
    creatorId: "u1",
    start: "TIET, Patiala",
    destination: "Manali",
    date: "2025-09-18",
    groupSize: 5,
    members: ["u1", "u5"],
    availableSeats: 3,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Chandigarh", "Kullu"],
    users: [{ id: "u1", gender: "female" }, { id: "u5", gender: "female" }],
  },
  {
    id: "t8",
    creatorId: "u2",
    start: "Patiala",
    destination: "Chandigarh",
    date: "2025-09-19",
    groupSize: 4,
    members: ["u2", "u3", "u6"],
    availableSeats: 1,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Rajpura", "Zirakpur"],
    users: [{ id: "u2", gender: "male" }, { id: "u3", gender: "male" }, { id: "u6", gender: "male" }],
  },
  {
    id: "t9",
    creatorId: "u9",
    start: "Chandigarh",
    destination: "Delhi",
    date: "2025-09-20",
    groupSize: 5,
    members: ["u9", "u10"],
    availableSeats: 3,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Panipat", "Sonipat"],
    users: [{ id: "u9", gender: "female" }, { id: "u10", gender: "male" }],
  },
  {
    id: "t10",
    creatorId: "u7",
    start: "TIET, Patiala",
    destination: "Mumbai",
    date: "2025-09-21",
    groupSize: 6,
    members: ["u7"],
    availableSeats: 5,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Jaipur", "Udaipur", "Surat"],
    users: [{ id: "u7", gender: "female" }],
  },

  // 11–28 additional trips
  {
    id: "t11",
    creatorId: "u5",
    start: "TIET, Patiala",
    destination: "Shimla",
    date: "2025-09-22",
    groupSize: 4,
    members: ["u5"],
    availableSeats: 3,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Chandigarh", "Solan"],
    users: [{ id: "u5", gender: "female" }],
  },
  {
    id: "t12",
    creatorId: "u6",
    start: "Patiala",
    destination: "Kurukshetra",
    date: "2025-09-22",
    groupSize: 3,
    members: ["u6"],
    availableSeats: 2,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Ambala"],
    users: [{ id: "u6", gender: "male" }],
  },
  {
    id: "t13",
    creatorId: "u3",
    start: "Chandigarh",
    destination: "Manali",
    date: "2025-09-23",
    groupSize: 5,
    members: ["u3", "u7"],
    availableSeats: 3,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Kullu"],
    users: [{ id: "u3", gender: "male" }, { id: "u7", gender: "female" }],
  },
  {
    id: "t14",
    creatorId: "u8",
    start: "TIET, Patiala",
    destination: "Dehradun",
    date: "2025-09-23",
    groupSize: 4,
    members: ["u8"],
    availableSeats: 3,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Ambala", "Haridwar"],
    users: [{ id: "u8", gender: "male" }],
  },
  {
    id: "t15",
    creatorId: "u9",
    start: "Chandigarh",
    destination: "Haridwar",
    date: "2025-09-24",
    groupSize: 3,
    members: ["u9"],
    availableSeats: 2,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Yamunanagar"],
    users: [{ id: "u9", gender: "female" }],
  },
  {
    id: "t16",
    creatorId: "u2",
    start: "Patiala",
    destination: "Jaipur",
    date: "2025-09-24",
    groupSize: 4,
    members: ["u2", "u10"],
    availableSeats: 2,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Rewari"],
    users: [{ id: "u2", gender: "male" }, { id: "u10", gender: "male" }],
  },
  {
    id: "t17",
    creatorId: "u1",
    start: "TIET, Patiala",
    destination: "Lucknow",
    date: "2025-09-25",
    groupSize: 5,
    members: ["u1", "u4"],
    availableSeats: 3,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Agra", "Kanpur"],
    users: [{ id: "u1", gender: "female" }, { id: "u4", gender: "female" }],
  },
  {
    id: "t18",
    creatorId: "u7",
    start: "Patiala",
    destination: "Ludhiana",
    date: "2025-09-25",
    groupSize: 3,
    members: ["u7", "u8"],
    availableSeats: 1,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Nabha"],
    users: [{ id: "u7", gender: "female" }, { id: "u8", gender: "male" }],
  },
  {
    id: "t19",
    creatorId: "u10",
    start: "TIET, Patiala",
    destination: "Varanasi",
    date: "2025-09-26",
    groupSize: 6,
    members: ["u10"],
    availableSeats: 5,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Meerut","Kanpur", "Allahabad"],
    users: [{ id: "u10", gender: "male" }],
  },
  {
    id: "t20",
    creatorId: "u5",
    start: "Patiala",
    destination: "Noida",
    date: "2025-09-26",
    groupSize: 4,
    members: ["u5", "u1"],
    availableSeats: 2,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Rajpura","Ambala","Kurukshetra","Karnal","Panipat","Sonipat","Delhi"],
    users: [{ id: "u5", gender: "female" }, { id: "u1", gender: "female" }],
  },
  {
    id: "t21",
    creatorId: "u6",
    start: "Chandigarh",
    destination: "Leh",
    date: "2025-09-27",
    groupSize: 5,
    members: ["u6", "u9"],
    availableSeats: 3,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Manali", "Keylong"],
    users: [{ id: "u6", gender: "male" }, { id: "u9", gender: "female" }],
  },
  {
    id: "t22",
    creatorId: "u3",
    start: "TIET, Patiala",
    destination: "Noida",
    date: "2025-09-27",
    groupSize: 4,
    members: ["u3"],
    availableSeats: 3,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Rajpura","Ambala","Kurukshetra","Karnal","Panipat","Sonipat","Delhi"],
    users: [{ id: "u3", gender: "male" }],
  },
  {
    id: "t23",
    creatorId: "u8",
    start: "Patiala",
    destination: "Gurgaon",
    date: "2025-09-28",
    groupSize: 3,
    members: ["u8", "u2"],
    availableSeats: 1,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Rajpura","Ambala","Kurukshetra","Karnal","Panipat","Sonipat","Delhi"],
    users: [{ id: "u8", gender: "male" }, { id: "u2", gender: "male" }],
  },
  {
    id: "t24",
    creatorId: "u4",
    start: "Chandigarh",
    destination: "Rishikesh",
    date: "2025-09-28",
    groupSize: 4,
    members: ["u4", "u5"],
    availableSeats: 2,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Haridwar"],
    users: [{ id: "u4", gender: "female" }, { id: "u5", gender: "female" }],
  },
  {
    id: "t25",
    creatorId: "u7",
    start: "TIET, Patiala",
    destination: "Kolkata",
    date: "2025-09-29",
    groupSize: 6,
    members: ["u7"],
    availableSeats: 5,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Varanasi", "Asansol"],
    users: [{ id: "u7", gender: "female" }],
  },
  {
    id: "t26",
    creatorId: "u9",
    start: "Patiala",
    destination: "Delhi",
    date: "2025-09-29",
    groupSize: 4,
    members: ["u9", "u1"],
    availableSeats: 2,
    isGirlsOnly: true,
    status: "OPEN",
    intermediateStops: ["Rajpura","Ambala","Kurukshetra","Karnal","Panipat","Sonipat"],
    users: [{ id: "u9", gender: "female" }, { id: "u1", gender: "female" }],
  },
  {
    id: "t27",
    creatorId: "u10",
    start: "Patiala",
    destination: "Chandigarh",
    date: "2025-09-30",
    groupSize: 3,
    members: ["u10", "u6"],
    availableSeats: 1,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Rajpura"],
    users: [{ id: "u10", gender: "male" }, { id: "u6", gender: "male" }],
  },
  {
    id: "t28",
    creatorId: "u2",
    start: "TIET, Patiala",
    destination: "Hyderabad",
    date: "2025-09-30",
    groupSize: 6,
    members: ["u2"],
    availableSeats: 5,
    isGirlsOnly: false,
    status: "OPEN",
    intermediateStops: ["Nagpur"],
    users: [{ id: "u2", gender: "male" }],
  },
];
